### PR TITLE
Travisty

### PR DESCRIPTION
**Pull request by CodaFi**
:warning: Don't Merge Until Travis Goes Green :warning:

### CODE REVIEW

**Comment by rsmoz** [comment]
Stripping the project of my name, how dare you! :stuck_out_tongue:

**Comment by CodaFi** [comment]
https://www.youtube.com/watch?v=QgTIhT5aLCg

**Comment by CodaFi** [comment]
In defiance of your earlier comments

:boat:

**Comment by rsmoz** [comment]
¯\_ಠ_ಠ_/¯

**Comment by rsmoz** [comment]
Text is hard.

**Comment by CodaFi** [comment]
Holy God, this will be here forever and I'm so god damn happy about it.

**Pull request merged**
